/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nbs;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Zero
 */
public class Lorry extends javax.swing.JFrame {

    /**
     * Creates new form Lorry
     */
    public Lorry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aaa = new javax.swing.JLabel();
        bbbb = new javax.swing.JLabel();
        vvvv = new javax.swing.JLabel();
        sakm = new javax.swing.JTextField();
        vvvvdd = new javax.swing.JLabel();
        clkm = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ldate = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        lmar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lmad = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lother = new javax.swing.JTextField();
        lregular = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        nol = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lds = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ldq = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lre = new javax.swing.JTextField();
        lorry = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aaa.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        aaa.setText("Lorry");

        bbbb.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        bbbb.setText("Date");

        vvvv.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        vvvv.setText("Starting KM");

        sakm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sakmActionPerformed(evt);
            }
        });

        vvvvdd.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        vvvvdd.setText("Closing KM ");

        clkm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clkmActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel5.setText("Maintance Regular");

        jLabel6.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel6.setText("Maintance Rate");

        lmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel7.setText("Description");

        lmad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lmadActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel8.setText("Other Alvance");

        lother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lotherActionPerformed(evt);
            }
        });

        lregular.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel9.setText("No. Load");

        nol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nolActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel10.setText("Diesel Rate");

        lds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldsActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel11.setText("Diesel Quantity");

        ldq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ldqActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Myriad Pro", 3, 14)); // NOI18N
        jLabel12.setText("Rent");

        lorry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "L1", "L2", "L3", "L4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aaa)
                    .addComponent(bbbb)
                    .addComponent(vvvv)
                    .addComponent(vvvvdd)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lregular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lmar)
                        .addComponent(sakm)
                        .addComponent(ldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(clkm)
                        .addComponent(lmad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lorry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lother)
                    .addComponent(nol)
                    .addComponent(lds)
                    .addComponent(ldq)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addComponent(lre))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lorry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bbbb)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sakm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vvvv)
                            .addComponent(jLabel10)
                            .addComponent(lds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clkm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vvvvdd)
                            .addComponent(jLabel11)
                            .addComponent(ldq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(lre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lregular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lmad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aaa)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(lother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(nol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(48, 48, 48))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sakmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sakmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sakmActionPerformed

    private void clkmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clkmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clkmActionPerformed

    private void lmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lmarActionPerformed

    private void lmadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lmadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lmadActionPerformed

    private void lotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lotherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lotherActionPerformed

    private void nolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nolActionPerformed

    private void ldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ldsActionPerformed

    private void ldqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ldqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ldqActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               // lorry name
              String lname=(String)lorry.getSelectedItem();
              //date
               Date oDate = ldate.getDate();        
               DateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
               String ldate = sdf.format(oDate);
               // st is strating km
          int shour=Integer.parseInt(sakm.getText());
          // cl is closing km
          int chour=Integer.parseInt(clkm.getText());
          // r is rent
          int rent=Integer.parseInt(lre.getText());
          // dr is diesel rate
          int drate=Integer.parseInt(lds.getText());
          //dq is diesel quantity 
          int dquant=Integer.parseInt(ldq.getText());
          // regular maintance
           String maregular=(String)l.getSelectedItem();
           // maintance rate
           int marate=Integer.parseInt(mrate.getText());
           // maintance Description
           String mades=mdes.getText();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lorry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lorry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aaa;
    private javax.swing.JLabel bbbb;
    private javax.swing.JTextField clkm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private org.jdesktop.swingx.JXDatePicker ldate;
    private javax.swing.JTextField ldq;
    private javax.swing.JTextField lds;
    private javax.swing.JTextField lmad;
    private javax.swing.JTextField lmar;
    private javax.swing.JComboBox<String> lorry;
    private javax.swing.JTextField lother;
    private javax.swing.JTextField lre;
    private javax.swing.JComboBox<String> lregular;
    private javax.swing.JTextField nol;
    private javax.swing.JTextField sakm;
    private javax.swing.JLabel vvvv;
    private javax.swing.JLabel vvvvdd;
    // End of variables declaration//GEN-END:variables
}
